### PR TITLE
Help berrack

### PR DESCRIPTION
**Pull request by st3107**

### CODE REVIEW

**Comment by st3107** [comment]
Hi @berrakozer . I suddenly realize that I cannot push my rebasing results as a PR becausee I am rebasing onto the master and it will have conflicts with your branch.

**Comment by berrakozer** [comment]
@st3107 what would you suggest me to do?

**Comment by st3107** [comment]
8:19
shall we have a zoom meeting now that I will show you how I did it and you can follow what I did in pycharm.

**Comment by berrakozer** [comment]
yes we can sending you the link!

**Pull request closed without merging**
